package com.msn.gabrielle.backend;

import java.io.Serializable;
import java.util.Objects;

public class Events {

	private Long id = null;
	private String title = ""; 
	private String location = "";
	private String description = "";
	private String url = "";
	int day, month, year;
	int hour, minute;
	
	//constructors
	
	public Events() {}
	
	public Events(String title, String location, 
			String description, String url, int day, int month, 
			int year, int hour, int min) {
		this.title = title;
		this.location = location;
		this.description = description;
		this.url = url;
		this.day = day;
		this.month = month;
		this.year = year;
		this.hour = hour;
		this.minute = minute;
	}
	
	//set methods
	
	public void setTitle(String newt) { title = newt;}
	
	public void setLocation(String newl) { location = newl;	}
	
	public void setDescription(String newd) { description = newd;}
	
	public void setUrl(String newu) { url = newu;}
	
	public void setDay(int newd) { day = newd;}
	
	public void setMonth(int newm) { month = newm;}
	
	public void setYear(int newy) { year = newy;}
	
	public void setHour(int newh) { hour = newh;}
	
	public void setMinute(int newmin) { minute = newmin;}
	
	//get methods
	
	public Long getId() { return this.id;}
	
	public String getTitle() { return this.title;}
	
	public String getLocation() { return this.location;}
	
	public String getDescription() { return this.description;}
	
	public String getUrl() { return this.url;}
	
	public int getDay() { return this.day;}
	
	public int getMonth() { return this.month;}
	
	public int getYear() { return this.year;}
	
	public int getHour() { return this.hour;}
	
	public int getMinute() { return this.minute;}
	
	@Override
    public String toString() {
        // Must use getters instead of direct member access,
        // to make it work with proxy objects generated by the view model
        return "Event{" + getId() + ":" + getTitle() + '}';
    }

    @Override
    public int hashCode() {
        if (getId() == null) {
            return super.hashCode();
        }
        return getId().hashCode();
    }

}
