package com.msn.gabrielle.backend;

import java.io.Serializable;
import java.util.Objects;

/**
 * Events.java - a simple class for creating Events Objects
 * @author Julianna Puleo
 *
 */

public class Events {

	private Long id = null;
	private String title = ""; 
	private String location = "";
	private String description = "";
	private String url = "";
	int day, month, year;
	int hour, minute;
	
	public Events() {}
	
	/**
	 * Create an Events object.
	 * @param title 		A variable of type String.
	 * @param location		A variable of type String.
	 * @param description	A variable of type String.
	 * @param url			A variable of type String.
	 * @param day			A variable of type int.
	 * @param month			A variable of type int.
	 * @param year			A variable of type int.
	 * @param hour			A variable of type int.
	 * @param min			A variable of type int.
	 */
	public Events(String title, String location, 
			String description, String url, int day, int month, 
			int year, int hour, int minute) {
		this.title = title;
		this.location = location;
		this.description = description;
		this.url = url;
		this.day = day;
		this.month = month;
		this.year = year;
		this.hour = hour;
		this.minute = minute;
	}
	
	//---------------- SET METHODS ----------------//
	
	/**
	 * Set the value of title.
	 * @param newt A variable of type String.
	 */
	public void setTitle(String newt) { title = newt;}
	
	/**
	 * Set the value of location.
	 * @param newt A variable of type String.
	 */
	public void setLocation(String newl) { location = newl;	}
	
	/**
	 * Set the value of description.
	 * @param newt A variable of type String.
	 */
	public void setDescription(String newd) { description = newd;}
	
	/**
	 * Set the value of URL.
	 * @param newt A variable of type String.
	 */
	public void setUrl(String newu) { url = newu;}
	
	/**
	 * Set the value of day.
	 * @param newt A variable of type int.
	 */
	public void setDay(int newd) { day = newd;}
	
	/**
	 * Set the value of month.
	 * @param newt A variable of type int.
	 */
	public void setMonth(int newm) { month = newm;}
	
	/**
	 * Set the value of year.
	 * @param newt A variable of type int.
	 */
	public void setYear(int newy) { year = newy;}
	
	/**
	 * Set the value of hour.
	 * @param newt A variable of type int.
	 */
	public void setHour(int newh) { hour = newh;}
	
	/**
	 * Set the value of minute.
	 * @param newt A variable of type int.
	 */
	public void setMinute(int newmin) { minute = newmin;}
	
	//---------------- GET METHODS ----------------//
	
	/**
	 * Retrieve the value of id.
	 * @return A Long data type.
	 */
	public Long getId() { return this.id;}
	
	/**
	 * Retrieve the value of title.
	 * @return A String data type.
	 */
	public String getTitle() { return this.title;}
	
	/**
	 * Retrieve the value of location.
	 * @return A String data type.
	 */
	public String getLocation() { return this.location;}
	
	/**
	 * Retrieve the value of description.
	 * @return A String data type.
	 */
	public String getDescription() { return this.description;}
	
	/**
	 * Retrieve the value of URL.
	 * @return A String data type.
	 */
	public String getUrl() { return this.url;}
	
	/**
	 * Retrieve the value of day.
	 * @return An int data type.
	 */
	public int getDay() { return this.day;}
	
	/**
	 * Retrieve the value of month.
	 * @return A int data type.
	 */
	public int getMonth() { return this.month;}
	
	/**
	 * Retrieve the value of year.
	 * @return A int data type.
	 */
	public int getYear() { return this.year;}
	
	/**
	 * Retrieve the value of hour.
	 * @return A int data type.
	 */
	public int getHour() { return this.hour;}
	
	/**
	 * Retrieve the value of minute.
	 * @return A int data type.
	 */
	public int getMinute() { return this.minute;}
	
//	@Override
//    public String toString() {
//        // Must use getters instead of direct member access,
//        // to make it work with proxy objects generated by the view model
//        return "Event{" + getId() + ":" + getTitle() + '}';
//    }
//
//    @Override
//    public int hashCode() {
//        if (getId() == null) {
//            return super.hashCode();
//        }
//        return getId().hashCode();
//    }

}
