package com.msn.gabrielle.backend;

import java.io.Serializable;
import java.util.Objects;

public class Projects implements Serializable {
	
	private Long id = null; //project id

    private String name = ""; //project name
    
    private String description = ""; //project description
    
    private String proposedBy = ""; //project proposer's name 
   
    private String location = "";
    
    private String date = "";
    
    private List<String> 

    public Projects() {
    }

    public Projects(String name, String String description, String proposedBy) {
        this.name = name;
        this.description = description;
        this.proposedBy = proposedBy;
    }

    public Projects(Projects other) {
        Objects.requireNonNull(other);
        this.name = other.getName();
        this.id = other.getId();
        this.description = other.getDescription();
        this.proposedBy = other.getProposedBy();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the value of the project name
     *
     * @return the value of the project name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value the project name
     *
     * @param name
     *            new value of the project name
     */
    public void setName(String name) {
        this.name = name;
    }
    
    /**
     * Gets the value of the project proposer
     *
     * @return the value of the project proposer
     */
    public String getProposedBy() {
        return proposedBy;
    }

    /**
     * Sets the value of the project proposer
     *
     * @param proposedBy
     *            new value value of the project proposer
     */
    public void setProposedBy(String proposedBy) {
        this.proposedBy = proposedBy;
    }
    
    /**
     * Gets the value of the project description
     *
     * @return the value of the project description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value name
     *
     * @param description
     *            new value of description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        // Must use getters instead of direct member access,
        // to make it work with proxy objects generated by the view model
        return "Project{" + getId() + ":" + getName() + '}';
    }

    @Override
    public int hashCode() {
        if (getId() == null) {
            return super.hashCode();
        }
        return getId().hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof Projects)) {
            return false;
        }
        Projects other = (Projects) obj;
        if (getId() == null) {
            if (other.getId() != null)
                return false;
        } else if (!getId().equals(other.getId()))
            return false;
        return true;
    }

}
